### ISSUE TITLE
Tag 6.0.0 build failed

### ISSUE THREAD

**Issue by Jamesits** [Unleash/unleash-docker-community#157]
### Describe the bug

It looks like that https://github.com/Unleash/unleash-docker-community/actions/runs/10196876369/job/28208525521 failed, resulting in 6.0.6 Docker images not being pushed.

### Subscription type

None

### Hosting type

None

**Comment by gastonfournier** [comment]
I believe this should fix it: https://github.com/Unleash/unleash-docker-community/pull/158

**Comment by Jamesits** [comment]
@gastonfournier Thanks for the quick response! The Docker image is still missing, is there any chance we re-run the failed jobs and get the images uploaded?

**Comment by gastonfournier** [comment]
@Jamesits there's tags for 6.0.6 that should be better than 6.0.0:

- https://hub.docker.com/r/unleashorg/unleash-community-openid-connect/tags
- https://hub.docker.com/r/unleashorg/unleash-community-azure/tags (this one also includes 6.0.0 which is the only one I was able to re-run)
- https://hub.docker.com/r/unleashorg/unleash-community-google/tags

**Comment by Jamesits** [comment]
Ah, didn't notice the new images are already available. Thank you very much!
